[package]
name = "ocr-parser-sandbox"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true
rust-version.workspace = true

[dependencies]
image.workspace = true
lopdf.workspace = true
ocr-domain = { path = "../ocr-domain" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
